version: 2

run:
  timeout: 5m
  tests: true

output:
  sort-results: true

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - misspell
  disable:
    - revive
    - errcheck
